### ISSUE TITLE
Drop support for Python 2 code 

### ISSUE THREAD

**Issue by pombredanne** [nexB/commoncode#8]
We have a branch that has all the needed changes in ScanCode in https://github.com/nexB/scancode-toolkit/pull/2167 by @Abhishek-Dev09 and that will need to be cherrypicked and filtered to keep the commoncode changes only.

@cco3 @tdruez FYI

**Comment by tdruez** [comment]
@pombredanne Make sure to merge https://github.com/nexB/commoncode/pull/7 as well for Python 3.9 compatibility.

**Comment by pombredanne** [comment]
Completed. Thanks!
